#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

START=91

USE_PROCD=1
PROG=/usr/bin/ECM_DEMO_AUTO

start_service() {
    procd_open_instance
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param command "$PROG" -L 4
    procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-5} ${respawn_retry:-100}
    procd_close_instance
}
